server:
  port: 8008
spring:
  application:
    name: j-cloud-stock
  datasource:
    #    url: jdbc:postgresql://49.234.17.178:5432/trade
    #   username: jiedong
    # password: ljd_yz2019
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123456

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka



mybatis:
  type-handlers-package: cn.ljd.framework.pghandler
  mapper-locations: classpath:mapper/*.xml

application-logging:
  logging.level.cn.ljd.framework: debug

logging:
  level:
    com.ljd.framework.mapper: info